package com.hsbc.core.dao;

import com.hsbc.core.bean.Orderdetail;
import com.hsbc.core.bean.OrderdetailQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int countByExample(OrderdetailQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int deleteByExample(OrderdetailQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int insert(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int insertSelective(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    List<Orderdetail> selectByExampleWithRowbounds(OrderdetailQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    List<Orderdetail> selectByExample(OrderdetailQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    Orderdetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") Orderdetail record, @Param("example") OrderdetailQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int updateByExample(@Param("record") Orderdetail record, @Param("example") OrderdetailQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int updateByPrimaryKeySelective(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Tue Aug 22 11:52:46 CST 2017
     */
    int updateByPrimaryKey(Orderdetail record);
}