package com.hsbc.core.dao;

import com.hsbc.core.bean.Items;
import com.hsbc.core.bean.ItemsQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int countByExample(ItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int deleteByExample(ItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int insert(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int insertSelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    List<Items> selectByExampleWithBLOBsWithRowbounds(ItemsQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    List<Items> selectByExampleWithBLOBs(ItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    List<Items> selectByExampleWithRowbounds(ItemsQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    List<Items> selectByExample(ItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    Items selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") Items record, @Param("example") ItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Items record, @Param("example") ItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByExample(@Param("record") Items record, @Param("example") ItemsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByPrimaryKeySelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByPrimaryKey(Items record);
}