package com.hsbc.core.dao;

import com.hsbc.core.bean.Orders;
import com.hsbc.core.bean.OrdersQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int countByExample(OrdersQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int deleteByExample(OrdersQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    List<Orders> selectByExampleWithRowbounds(OrdersQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    List<Orders> selectByExample(OrdersQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    Orders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Sep 01 09:46:19 CST 2017
     */
    int updateByPrimaryKey(Orders record);
}